// playgrounds/solidstart-demo/src/routes/structured.tsx
import { useStructuredStream } from "@aibind/solidstart";
import { Show, createSignal } from "solid-js";
import { z } from "zod";

const AnalysisSchema = z.object({
  sentiment: z.enum(["positive", "negative", "neutral"]),
  score: z.number(),
  topics: z.array(z.string()),
  summary: z.string(),
});

export default function StructuredPage() {
  const { partial, loading, error, send, retry } = useStructuredStream({
    schema: AnalysisSchema,
    system:
      "You are a sentiment analysis expert. Return valid JSON matching the schema.",
  });

  const [text, setText] = createSignal("");

  return (
    <div>
      <h1>StructuredStream Demo</h1>

      <form
        onSubmit={(e) => {
          e.preventDefault();
          send(`Analyze this text: ${text()}`);
        }}
        style={{
          display: "flex",
          "flex-direction": "column",
          gap: "0.5rem",
          "margin-bottom": "1rem",
        }}
      >
        <textarea
          value={text()}
          onInput={(e) => setText(e.currentTarget.value)}
          placeholder="Paste text to analyze..."
          rows="4"
          style={{ padding: "0.5rem" }}
        />
        <button type="submit" disabled={loading()}>
          {loading() ? "Analyzing..." : "Analyze"}
        </button>
      </form>

      <Show when={partial()}>
        <div
          style={{
            padding: "1rem",
            background: "#f9fafb",
            "border-radius": "0.5rem",
            opacity: loading() ? "0.7" : "1",
          }}
        >
          <Show when={partial()!.sentiment}>
            <p>
              <strong>Sentiment:</strong> {partial()!.sentiment}
            </p>
          </Show>
          <Show when={partial()!.score != null}>
            <p>
              <strong>Score:</strong> {partial()!.score}
            </p>
          </Show>
          <Show when={partial()!.summary}>
            <p>
              <strong>Summary:</strong> {partial()!.summary}
            </p>
          </Show>
          <Show when={partial()!.topics?.length}>
            <p>
              <strong>Topics:</strong> {partial()!.topics!.join(", ")}
            </p>
          </Show>
        </div>
      </Show>

      <Show when={error()}>
        <div style={{ color: "#dc2626", padding: "1rem" }}>
          <p>{error()!.message}</p>
          <button onClick={() => retry()}>Retry</button>
        </div>
      </Show>
    </div>
  );
}

// playgrounds/demo/src/routes/structured/+page.svelte
<script lang="ts">
	import { StructuredStream } from '@aibind/svelte';
	import { z } from 'zod/v4';

	const AnalysisSchema = z.object({
		sentiment: z.enum(['positive', 'negative', 'neutral']),
		score: z.number(),
		topics: z.array(z.string()),
		summary: z.string(),
	});

	const analysis = new StructuredStream({
		schema: AnalysisSchema,
		system: 'You are a sentiment analysis expert. Return valid JSON matching the schema.',
	});

	let text = $state('');
</script>

<h1>StructuredStream Demo</h1>

<form
	onsubmit={(e) => {
		e.preventDefault();
		analysis.send(`Analyze this text: ${text}`);
	}}
>
	<textarea bind:value={text} placeholder="Paste text to analyze..." rows="4"></textarea>
	<button type="submit" disabled={analysis.loading}>
		{analysis.loading ? 'Analyzing...' : 'Analyze'}
	</button>
</form>

{#if analysis.partial}
	<div class="result" class:loading={analysis.loading}>
		{#if analysis.partial.sentiment}
			<p><strong>Sentiment:</strong> {analysis.partial.sentiment}</p>
		{/if}
		{#if analysis.partial.score != null}
			<p><strong>Score:</strong> {analysis.partial.score}</p>
		{/if}
		{#if analysis.partial.summary}
			<p><strong>Summary:</strong> {analysis.partial.summary}</p>
		{/if}
		{#if analysis.partial.topics?.length}
			<p><strong>Topics:</strong> {analysis.partial.topics.join(', ')}</p>
		{/if}
	</div>
{/if}

{#if analysis.error}
	<div class="error">
		<p>{analysis.error.message}</p>
		<button onclick={() => analysis.retry()}>Retry</button>
	</div>
{/if}

<style>
	form {
		display: flex;
		flex-direction: column;
		gap: 0.5rem;
		margin-bottom: 1rem;
	}
	textarea {
		padding: 0.5rem;
	}
	.result {
		padding: 1rem;
		background: #f9fafb;
		border-radius: 0.5rem;
	}
	.loading {
		opacity: 0.7;
	}
	.error {
		color: #dc2626;
		padding: 1rem;
	}
</style>
