// playgrounds/solidstart-demo/src/routes/index.tsx
export default function Home() {
  return (
    <div>
      <h1>aibind SolidStart Playground</h1>
      <p>Test the @aibind/solidstart library features:</p>
      <ul>
        <li><a href="/stream">Stream — streaming text</a></li>
        <li><a href="/structured">StructuredStream — typed partial streaming</a></li>
        <li><a href="/agent">Agent — tool-calling agent with weather & time</a></li>
        <li><a href="/markdown">Markdown — streaming markdown rendering</a></li>
      </ul>
    </div>
  );
}

// playgrounds/sveltekit-demo/src/routes/+page.svelte
<h1>svai Playground</h1>
<p>Test the svai library features:</p>
<ul>
	<li><a href="/stream">Stream — streaming text</a></li>
	<li><a href="/structured">StructuredStream — typed partial streaming</a></li>
	<li><a href="/agent">Agent — tool-calling agent with weather & time</a></li>
	<li><a href="/query">Query — remote query & structured query</a></li>
	<li><a href="/markdown">Markdown — streaming markdown rendering</a></li>
</ul>
