// playgrounds/demo/src/routes/stream/+page.svelte
<script lang="ts">
	import { Stream } from '@aibind/svelte';

	const stream = new Stream({
		system: 'You are a helpful assistant. Keep responses concise.',
		model: 'gpt',
	});

	let prompt = $state('');
</script>

<h1>Stream Demo</h1>

<form
	onsubmit={(e) => {
		e.preventDefault();
		stream.send(prompt);
		prompt = '';
	}}
>
	<input bind:value={prompt} placeholder="Ask something..." />
	<button type="submit" disabled={stream.loading}>
		{stream.loading ? 'Streaming...' : 'Send'}
	</button>
	{#if stream.loading}
		<button type="button" onclick={() => stream.abort()}>Stop</button>
	{/if}
</form>

{#if stream.text}
	<div class="response" class:streaming={stream.loading}>
		{stream.text}{#if stream.loading}▌{/if}
	</div>
{/if}

{#if stream.error}
	<div class="error">
		<p>{stream.error.message}</p>
		<button onclick={() => stream.retry()}>Retry</button>
	</div>
{/if}

<style>
	form {
		display: flex;
		gap: 0.5rem;
		margin-bottom: 1rem;
	}
	input {
		flex: 1;
		padding: 0.5rem;
	}
	.response {
		padding: 1rem;
		background: #f9fafb;
		border-radius: 0.5rem;
		white-space: pre-wrap;
	}
	.streaming {
		opacity: 0.8;
	}
	.error {
		color: #dc2626;
		padding: 1rem;
	}
</style>

// playgrounds/nextjs-demo/src/app/stream/page.tsx
"use client";

import { useState } from "react";
import { useStream } from "@aibind/nextjs";

export default function StreamPage() {
  const [prompt, setPrompt] = useState("");
  const stream = useStream({
    system: "You are a helpful assistant. Keep responses concise.",
    model: "gpt",
  });

  return (
    <div>
      <h1>Stream Demo</h1>
      <form
        onSubmit={(e) => {
          e.preventDefault();
          stream.send(prompt);
          setPrompt("");
        }}
        style={{ display: "flex", gap: "0.5rem", marginBottom: "1rem" }}
      >
        <input
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder="Ask something..."
          style={{ flex: 1, padding: "0.5rem" }}
        />
        <button type="submit" disabled={stream.loading}>
          {stream.loading ? "Streaming..." : "Send"}
        </button>
        {stream.loading && (
          <button type="button" onClick={() => stream.abort()}>
            Stop
          </button>
        )}
      </form>

      {stream.text && (
        <div
          style={{
            padding: "1rem",
            background: "#f9fafb",
            borderRadius: "0.5rem",
            whiteSpace: "pre-wrap",
            opacity: stream.loading ? 0.8 : 1,
          }}
        >
          {stream.text}
          {stream.loading && "▌"}
        </div>
      )}

      {stream.error && (
        <div style={{ color: "#dc2626", padding: "1rem" }}>
          <p>{stream.error.message}</p>
          <button onClick={() => stream.retry()}>Retry</button>
        </div>
      )}
    </div>
  );
}
