// playgrounds/nuxt-demo/pages/markdown.vue
<script setup lang="ts">
import { useStream } from "@aibind/nuxt";
import { StreamMarkdown } from "@aibind/nuxt/markdown";

const { text, loading, error, send, abort, retry } = useStream({
  system:
    "You are a helpful assistant. Always respond with rich markdown formatting: use headings, **bold**, *italic*, `inline code`, code blocks with language tags, bullet lists, and numbered lists where appropriate.",
  model: "gpt",
});

const prompt = ref("");

function handleSubmit() {
  send(prompt.value);
  prompt.value = "";
}
</script>

<template>
  <div>
    <h1>Markdown Demo</h1>
    <p>
      Streaming markdown with live recovery — unterminated syntax renders
      gracefully.
    </p>

    <form @submit.prevent="handleSubmit">
      <input
        v-model="prompt"
        placeholder="Ask something (try 'explain async/await')..."
      />
      <button type="submit" :disabled="loading">
        {{ loading ? "Streaming..." : "Send" }}
      </button>
      <button v-if="loading" type="button" @click="abort()">Stop</button>
    </form>

    <div v-if="text" class="response">
      <StreamMarkdown :text="text" :streaming="loading" />
    </div>

    <div v-if="error" class="error">
      <p>{{ error.message }}</p>
      <button @click="retry()">Retry</button>
    </div>
  </div>
</template>

<style scoped>
form {
  display: flex;
  gap: 0.5rem;
  margin-bottom: 1rem;
}
input {
  flex: 1;
  padding: 0.5rem;
}
.response {
  padding: 1rem;
  background: #f9fafb;
  border-radius: 0.5rem;
}
.response :deep(pre) {
  background: #1f2937;
  color: #f9fafb;
  padding: 1rem;
  border-radius: 0.375rem;
  overflow-x: auto;
}
.response :deep(code) {
  font-size: 0.875rem;
}
.response :deep(p code) {
  background: #e5e7eb;
  padding: 0.125rem 0.25rem;
  border-radius: 0.25rem;
}
.error {
  color: #dc2626;
  padding: 1rem;
}
</style>

// playgrounds/solidstart-demo/src/routes/markdown.tsx
import { useStream } from '@aibind/solidstart';
import { useStreamMarkdown } from '@aibind/solidstart/markdown';
import { Show, createSignal } from 'solid-js';

export default function MarkdownPage() {
  const { text, loading, error, send, abort, retry } = useStream({
    system: 'You are a helpful assistant. Always respond with rich markdown formatting: use headings, **bold**, *italic*, `inline code`, code blocks with language tags, bullet lists, and numbered lists where appropriate.',
    model: 'gpt',
  });

  const html = useStreamMarkdown(() => text(), () => loading());
  const [prompt, setPrompt] = createSignal('');

  function handleSubmit(e: SubmitEvent) {
    e.preventDefault();
    send(prompt());
    setPrompt('');
  }

  return (
    <div>
      <h1>Markdown Demo</h1>
      <p>Streaming markdown with live recovery — unterminated syntax renders gracefully.</p>

      <form onSubmit={handleSubmit} style={{ display: "flex", gap: "0.5rem", "margin-bottom": "1rem" }}>
        <input
          value={prompt()}
          onInput={(e) => setPrompt(e.currentTarget.value)}
          placeholder="Ask something (try 'explain async/await')..."
          style={{ flex: "1", padding: "0.5rem" }}
        />
        <button type="submit" disabled={loading()}>
          {loading() ? 'Streaming...' : 'Send'}
        </button>
        <Show when={loading()}>
          <button type="button" onClick={() => abort()}>Stop</button>
        </Show>
      </form>

      <Show when={text()}>
        <div
          style={{
            padding: "1rem",
            background: "#f9fafb",
            "border-radius": "0.5rem",
          }}
          innerHTML={html()}
        />
      </Show>

      <Show when={error()}>
        <div style={{ color: "#dc2626", padding: "1rem" }}>
          <p>{error()!.message}</p>
          <button onClick={() => retry()}>Retry</button>
        </div>
      </Show>
    </div>
  );
}
