// playgrounds/nuxt-demo/pages/stream.vue
<script setup lang="ts">
import { useStream } from '@aibind/nuxt';

const { text, loading, error, send, abort, retry } = useStream({
  system: 'You are a helpful assistant. Keep responses concise.',
  model: 'gpt',
});

const prompt = ref('');

function handleSubmit() {
  send(prompt.value);
  prompt.value = '';
}
</script>

<template>
  <div>
    <h1>Stream Demo</h1>

    <form @submit.prevent="handleSubmit">
      <input v-model="prompt" placeholder="Ask something..." />
      <button type="submit" :disabled="loading">
        {{ loading ? 'Streaming...' : 'Send' }}
      </button>
      <button v-if="loading" type="button" @click="abort()">Stop</button>
    </form>

    <div v-if="text" class="response" :class="{ streaming: loading }">
      {{ text }}<span v-if="loading">▌</span>
    </div>

    <div v-if="error" class="error">
      <p>{{ error.message }}</p>
      <button @click="retry()">Retry</button>
    </div>
  </div>
</template>

<style scoped>
form {
  display: flex;
  gap: 0.5rem;
  margin-bottom: 1rem;
}
input {
  flex: 1;
  padding: 0.5rem;
}
.response {
  padding: 1rem;
  background: #f9fafb;
  border-radius: 0.5rem;
  white-space: pre-wrap;
}
.streaming {
  opacity: 0.8;
}
.error {
  color: #dc2626;
  padding: 1rem;
}
</style>

// playgrounds/solidstart-demo/src/routes/stream.tsx
import { useStream } from '@aibind/solidstart';
import { Show, createSignal } from 'solid-js';

export default function StreamPage() {
  const { text, loading, error, send, abort, retry } = useStream({
    system: 'You are a helpful assistant. Keep responses concise.',
    model: 'gpt',
  });

  const [prompt, setPrompt] = createSignal('');

  function handleSubmit(e: SubmitEvent) {
    e.preventDefault();
    send(prompt());
    setPrompt('');
  }

  return (
    <div>
      <h1>Stream Demo</h1>

      <form onSubmit={handleSubmit} style={{ display: "flex", gap: "0.5rem", "margin-bottom": "1rem" }}>
        <input
          value={prompt()}
          onInput={(e) => setPrompt(e.currentTarget.value)}
          placeholder="Ask something..."
          style={{ flex: 1, padding: "0.5rem" }}
        />
        <button type="submit" disabled={loading()}>
          {loading() ? 'Streaming...' : 'Send'}
        </button>
        <Show when={loading()}>
          <button type="button" onClick={() => abort()}>Stop</button>
        </Show>
      </form>

      <Show when={text()}>
        <div style={{
          padding: "1rem",
          background: "#f9fafb",
          "border-radius": "0.5rem",
          "white-space": "pre-wrap",
          opacity: loading() ? "0.8" : "1",
        }}>
          {text()}<Show when={loading()}>▌</Show>
        </div>
      </Show>

      <Show when={error()}>
        <div style={{ color: "#dc2626", padding: "1rem" }}>
          <p>{error()!.message}</p>
          <button onClick={() => retry()}>Retry</button>
        </div>
      </Show>
    </div>
  );
}
