// packages/solid/src/history/chat-history.ts
import { createSignal, createMemo, type Accessor } from "solid-js";
import { ChatHistory as CoreChatHistory, type TreeConfig } from "@aibind/core";

/**
 * SolidJS reactive wrapper around {@link ChatHistory}.
 *
 * All mutations automatically trigger reactive updates via SolidJS signals.
 * Derived state (`messages`, `nodeIds`, `isEmpty`, `size`) are exposed as
 * `Accessor` functions that update when the underlying data changes.
 *
 * Access the underlying `ChatHistory` via the `inner` property for
 * non-reactive operations or direct tree access.
 *
 * @example
 * ```tsx
 * import { ChatHistory } from '@aibind/solid/history';
 *
 * function Chat() {
 *   const chat = new ChatHistory<{ role: string; content: string }>();
 *
 *   const m1 = chat.append({ role: 'user', content: 'Hello' });
 *   // chat.messages() is reactive — UI updates automatically
 *
 *   return (
 *     <div>
 *       <For each={chat.messages()}>
 *         {(msg, i) => (
 *           <div>
 *             {msg.role}: {msg.content}
 *             {chat.hasAlternatives(chat.nodeIds()[i()]) && (
 *               <>
 *                 <button onClick={() => chat.prevAlternative(chat.nodeIds()[i()])}>Prev</button>
 *                 <span>
 *                   {chat.alternativeIndex(chat.nodeIds()[i()]) + 1}
 *                   /{chat.alternativeCount(chat.nodeIds()[i()])}
 *                 </span>
 *                 <button onClick={() => chat.nextAlternative(chat.nodeIds()[i()])}>Next</button>
 *               </>
 *             )}
 *           </div>
 *         )}
 *       </For>
 *     </div>
 *   );
 * }
 * ```
 */
export class ChatHistory<M> {
  /** The underlying non-reactive ChatHistory. */
  readonly inner: CoreChatHistory<M>;

  private _getVersion: Accessor<number>;
  private _setVersion: (v: number | ((prev: number) => number)) => void;

  // ─── Reactive Accessors ──────────────────────────────────────

  /** Linear message path from root to active leaf. Reactive accessor. */
  readonly messages: Accessor<M[]>;

  /** Node IDs corresponding to each message in the active path. Reactive accessor. */
  readonly nodeIds: Accessor<string[]>;

  /** Whether the history is empty. Reactive accessor. */
  readonly isEmpty: Accessor<boolean>;

  /** Total number of messages across all branches. Reactive accessor. */
  readonly size: Accessor<number>;

  constructor(config?: TreeConfig) {
    this.inner = new CoreChatHistory<M>(config);

    const [getVersion, setVersion] = createSignal(0);
    this._getVersion = getVersion;
    this._setVersion = setVersion;

    this.messages = createMemo(() => {
      getVersion();
      return this.inner.messages;
    });
    this.nodeIds = createMemo(() => {
      getVersion();
      return this.inner.nodeIds;
    });
    this.isEmpty = createMemo(() => {
      getVersion();
      return this.inner.isEmpty;
    });
    this.size = createMemo(() => {
      getVersion();
      return this.inner.size;
    });
  }

  // ─── Mutations (trigger reactivity) ─────────────────────────

  /**
   * Append a message to the current conversation path.
   * @returns The new node's ID.
   */
  append(message: M): string {
    const id = this.inner.append(message);
    this._setVersion((v) => v + 1);
    return id;
  }

  /**
   * Edit a message by creating a new branch from its parent.
   * The edited message becomes a sibling of the original.
   * Sets the new branch as active.
   *
   * @param messageId - ID of the message to "edit" (a sibling will be created).
   * @param newMessage - The replacement message content.
   * @returns The new node's ID.
   * @throws If messageId does not exist.
   */
  edit(messageId: string, newMessage: M): string {
    const id = this.inner.edit(messageId, newMessage);
    this._setVersion((v) => v + 1);
    return id;
  }

  /**
   * Regenerate a response by creating a new branch from its parent.
   * Semantically identical to `edit()` — creates a sibling alternative.
   *
   * @param messageId - ID of the message to regenerate (a sibling will be created).
   * @param newResponse - The new response content.
   * @returns The new node's ID.
   * @throws If messageId does not exist.
   */
  regenerate(messageId: string, newResponse: M): string {
    const id = this.inner.regenerate(messageId, newResponse);
    this._setVersion((v) => v + 1);
    return id;
  }

  // ─── Alternative Navigation ─────────────────────────────────

  /** Whether a message has alternative siblings (branches). */
  hasAlternatives(nodeId: string): boolean {
    return this.inner.hasAlternatives(nodeId);
  }

  /** Total number of alternatives (siblings) for a message. */
  alternativeCount(nodeId: string): number {
    return this.inner.alternativeCount(nodeId);
  }

  /** 0-based index of a message among its siblings. */
  alternativeIndex(nodeId: string): number {
    return this.inner.alternativeIndex(nodeId);
  }

  /**
   * Switch to the next alternative (right) and follow to leaf.
   * Updates the active path.
   * @throws If nodeId does not exist.
   */
  nextAlternative(nodeId: string): void {
    this.inner.nextAlternative(nodeId);
    this._setVersion((v) => v + 1);
  }

  /**
   * Switch to the previous alternative (left) and follow to leaf.
   * Updates the active path.
   * @throws If nodeId does not exist.
   */
  prevAlternative(nodeId: string): void {
    this.inner.prevAlternative(nodeId);
    this._setVersion((v) => v + 1);
  }

  // ─── Persistence ────────────────────────────────────────────

  /** Serialize to a JSON string. */
  toJSON(): string {
    return this.inner.toJSON();
  }

  /** Restore from a JSON string. Returns a new reactive instance. */
  static fromJSON<M>(json: string, config?: TreeConfig): ChatHistory<M> {
    const instance = new ChatHistory<M>(config);
    const restored = CoreChatHistory.fromJSON<M>(json, config);
    (instance as { inner: CoreChatHistory<M> }).inner = restored;
    // Bump version so memos re-evaluate with the restored inner tree
    instance._setVersion((v) => v + 1);
    return instance;
  }
}

// packages/react/src/history/chat-history.ts
import { useSyncExternalStore } from "react";
import { ChatHistory as CoreChatHistory, type TreeConfig } from "@aibind/core";

/**
 * React reactive wrapper around {@link CoreChatHistory}.
 *
 * All mutations automatically trigger re-renders via `useSyncExternalStore`.
 * Call `useSnapshot()` inside a component to get reactive state.
 *
 * @example
 * ```tsx
 * const chat = new ChatHistory<{ role: string; content: string }>();
 *
 * function Chat() {
 *   const { messages, nodeIds } = chat.useSnapshot();
 *
 *   return (
 *     <div>
 *       {messages.map((msg, i) => (
 *         <div key={nodeIds[i]}>
 *           {msg.role}: {msg.content}
 *         </div>
 *       ))}
 *     </div>
 *   );
 * }
 * ```
 */
export class ChatHistory<M> {
  /** The underlying non-reactive ChatHistory. */
  readonly inner: CoreChatHistory<M>;

  private _version = 0;
  private _listeners = new Set<() => void>();

  constructor(config?: TreeConfig) {
    this.inner = new CoreChatHistory<M>(config);
  }

  private _notify(): void {
    this._version++;
    this._listeners.forEach((l) => l());
  }

  /** Subscribe to changes (for useSyncExternalStore). */
  readonly subscribe = (listener: () => void): (() => void) => {
    this._listeners.add(listener);
    return () => this._listeners.delete(listener);
  };

  /** Get the current snapshot version (for useSyncExternalStore). */
  readonly getSnapshot = (): number => this._version;

  // ─── React Hook ────────────────────────────────────────────

  /**
   * React hook — call inside components to get reactive state.
   * Re-renders the component when the history changes.
   */
  useSnapshot(): {
    messages: M[];
    nodeIds: string[];
    isEmpty: boolean;
    size: number;
  } {
    useSyncExternalStore(this.subscribe, this.getSnapshot);
    return {
      messages: this.inner.messages,
      nodeIds: this.inner.nodeIds,
      isEmpty: this.inner.isEmpty,
      size: this.inner.size,
    };
  }

  // ─── Mutations (trigger reactivity) ─────────────────────────

  /** Append a message to the current conversation path. */
  append(message: M): string {
    const id = this.inner.append(message);
    this._notify();
    return id;
  }

  /** Edit a message by creating a new branch from its parent. */
  edit(messageId: string, newMessage: M): string {
    const id = this.inner.edit(messageId, newMessage);
    this._notify();
    return id;
  }

  /** Regenerate a response by creating a new branch from its parent. */
  regenerate(messageId: string, newResponse: M): string {
    const id = this.inner.regenerate(messageId, newResponse);
    this._notify();
    return id;
  }

  // ─── Alternative Navigation ─────────────────────────────────

  /** Whether a message has alternative siblings (branches). */
  hasAlternatives(nodeId: string): boolean {
    return this.inner.hasAlternatives(nodeId);
  }

  /** Total number of alternatives (siblings) for a message. */
  alternativeCount(nodeId: string): number {
    return this.inner.alternativeCount(nodeId);
  }

  /** 0-based index of a message among its siblings. */
  alternativeIndex(nodeId: string): number {
    return this.inner.alternativeIndex(nodeId);
  }

  /** Switch to the next alternative (right) and follow to leaf. */
  nextAlternative(nodeId: string): void {
    this.inner.nextAlternative(nodeId);
    this._notify();
  }

  /** Switch to the previous alternative (left) and follow to leaf. */
  prevAlternative(nodeId: string): void {
    this.inner.prevAlternative(nodeId);
    this._notify();
  }

  // ─── Persistence ────────────────────────────────────────────

  /** Serialize to a JSON string. */
  toJSON(): string {
    return this.inner.toJSON();
  }

  /** Restore from a JSON string. Returns a new reactive instance. */
  static fromJSON<M>(json: string, config?: TreeConfig): ChatHistory<M> {
    const instance = new ChatHistory<M>(config);
    const restored = CoreChatHistory.fromJSON<M>(json, config);
    (instance as { inner: CoreChatHistory<M> }).inner = restored;
    instance._version++;
    return instance;
  }
}
