// packages/react/src/agent/use-agent.ts
import { useState, useEffect, useRef } from "react";
import {
  AgentController,
  type AgentCallbacks,
  type AgentStatus,
  type AgentMessage,
  type AgentOptions,
} from "@aibind/core";

export type { AgentOptions } from "@aibind/core";

export interface UseAgentReturn {
  messages: AgentMessage[];
  status: AgentStatus;
  error: Error | null;
  pendingApproval: { id: string; toolName: string; args: unknown } | null;
  /** The name of the graph node currently executing, or `null` when idle. */
  currentNode: string | null;
  send: (prompt: string) => Promise<void>;
  stop: () => void;
  approve: (id: string) => void;
  deny: (id: string, reason?: string) => void;
}

/**
 * React hook for interacting with a server-side AI agent.
 *
 * @example
 * ```tsx
 * const { messages, send, status } = useAgent({ endpoint: '/api/agent' });
 * ```
 */
export function useAgent(options: AgentOptions): UseAgentReturn {
  const [messages, setMessages] = useState<AgentMessage[]>([]);
  const [status, setStatus] = useState<AgentStatus>("idle");
  const [error, setError] = useState<Error | null>(null);
  const [pendingApproval, setPendingApproval] = useState<{
    id: string;
    toolName: string;
    args: unknown;
  } | null>(null);
  const [currentNode, setCurrentNode] = useState<string | null>(null);

  const ctrlRef = useRef<AgentController | null>(null);

  if (!ctrlRef.current) {
    ctrlRef.current = new AgentController(options, {
      onMessages: setMessages,
      onStatus: setStatus,
      onError: setError,
      onPendingApproval: setPendingApproval,
      onCurrentNode: setCurrentNode,
    } satisfies AgentCallbacks);
  }

  useEffect(() => () => ctrlRef.current?.stop(), []);

  // We need refs for approve/deny since they access current state
  const stateRef = useRef({ pendingApproval, status });
  stateRef.current = { pendingApproval, status };

  return {
    messages,
    status,
    error,
    pendingApproval,
    currentNode,
    send: (prompt: string) => ctrlRef.current!.send(prompt),
    stop: () => ctrlRef.current!.stop(),
    approve: (id: string) => {
      ctrlRef.current!.setPendingApproval(stateRef.current.pendingApproval);
      ctrlRef.current!.setStatus(stateRef.current.status);
      ctrlRef.current!.approve(id);
    },
    deny: (id: string, reason?: string) => {
      ctrlRef.current!.setPendingApproval(stateRef.current.pendingApproval);
      ctrlRef.current!.setStatus(stateRef.current.status);
      ctrlRef.current!.deny(id, reason);
    },
  };
}

// packages/solid/src/agent/use-agent.ts
import { createSignal, onCleanup } from "solid-js";
import type { Accessor } from "solid-js";
import {
  AgentController,
  type AgentCallbacks,
  type AgentStatus,
  type AgentMessage,
  type AgentOptions,
} from "@aibind/core";

export type { AgentOptions } from "@aibind/core";

export interface UseAgentReturn {
  messages: Accessor<AgentMessage[]>;
  status: Accessor<AgentStatus>;
  error: Accessor<Error | null>;
  pendingApproval: Accessor<{
    id: string;
    toolName: string;
    args: unknown;
  } | null>;
  /** The name of the graph node currently executing, or `null` when idle. */
  currentNode: Accessor<string | null>;
  send: (prompt: string) => Promise<void>;
  stop: () => void;
  approve: (id: string) => void;
  deny: (id: string, reason?: string) => void;
}

/**
 * Reactive agent hook.
 * Streams responses from a server-side agent endpoint.
 * Call inside a component.
 */
export function useAgent(options: AgentOptions): UseAgentReturn {
  const [messages, setMessages] = createSignal<AgentMessage[]>([]);
  const [status, setStatus] = createSignal<AgentStatus>("idle");
  const [error, setError] = createSignal<Error | null>(null);
  const [pendingApproval, setPendingApproval] = createSignal<{
    id: string;
    toolName: string;
    args: unknown;
  } | null>(null);
  const [currentNode, setCurrentNode] = createSignal<string | null>(null);

  const ctrl = new AgentController(options, {
    onMessages: (m) => setMessages(m),
    onStatus: (s) => setStatus(s),
    onError: (e) => setError(e),
    onPendingApproval: (pa) => setPendingApproval(pa),
    onCurrentNode: (node) => setCurrentNode(node),
  } satisfies AgentCallbacks);

  onCleanup(() => ctrl.stop());

  return {
    messages,
    status,
    error,
    pendingApproval,
    currentNode,
    send: (prompt: string) => ctrl.send(prompt),
    stop: () => ctrl.stop(),
    approve: (id: string) => {
      ctrl.setPendingApproval(pendingApproval());
      ctrl.setStatus(status());
      ctrl.approve(id);
    },
    deny: (id: string, reason?: string) => {
      ctrl.setPendingApproval(pendingApproval());
      ctrl.setStatus(status());
      ctrl.deny(id, reason);
    },
  };
}
